SEED: 1
RESULT_DIR: results/
FIG_DIR: figs/
RUN_DIR: runs/
DATA:
  RAT: '025'
  TEST_FOLD: 1
  DAY: '2020-07-16'
  TASK: 1MC
PREPROCESS:
  BIN_SIZE: 0.1
  BEFORE_CUE_LONG: 2
  BEFORE_CUE: 0
  AFTER_CUE: 0
  BEFORE_PRESS: 1
  AFTER_PRESS: 0.5
  AFTER_RELEASE: 1
  AFTER_RELEASE_LONG: 2
model:
  hidden_layer_list:
  - 32
  - 16
  activation: tanh
  dim_y: 16
  dim_a: 6
  init_A_scale: 1
  init_C_scale: 1
  init_W_scale: 0.5
  init_R_scale: 0.5
  init_cov: 1
  is_W_trainable: true
  is_R_trainable: true
  ldm_kernel_initializer: default
  nn_kernel_initializer: xavier_normal
  supervise_behv: false
  hidden_layer_list_mapper:
  - 20
  - 20
  - 20
  activation_mapper: tanh
  which_behv_dims:
  - 0
  - 1
  - 2
  - 3
  behv_from_smooth: true
  save_steps: 10
MODEL:
  LATENT_DIM: 6
  TIME_WINDOW: 25
loss:
  scale_l2: 0.2
  steps_ahead:
  - 1
  scale_behv_recons: 20
TRAIN:
  NUM_UPDATES: 25
  CLIP_GRAD_NORM: 0.5
  BATCH_SIZE: 128
  BATCH_SIZE_TEST: 1000000
  STEP_SIZE: 1
  STEP_SIZE_TEST: 10
  VAL_INTERVAL: 5
  LOGS_PER_EPOCH: 4
  WEIGHT_DECAY: 0.01
  LR:
    INIT: 0.005
    SCHEDULE: true
    SCHEDULER: cosine
    WARMUP: 10
