SEED: 1
RESULT_DIR: results/
FIG_DIR: figs/
RUN_DIR: runs/
DATA:
  RAT: '025'
  TEST_FOLD: 0
  DAY: '2020-07-16'
  TASK: 1MC
PREPROCESS:
  BIN_SIZE: 0.1
  BEFORE_CUE_LONG: 2
  BEFORE_CUE: 0
  AFTER_CUE: 0
  BEFORE_PRESS: 1
  AFTER_PRESS: 0.5
  AFTER_RELEASE: 1
  AFTER_RELEASE_LONG: 2
MODEL:
  NAME: stVAE
  VARIATIONAL: true
  HIDDEN_SIZE: 64
  DROPOUT: 0
  NUM_HEADS: 2
  N_LAYERS_ENCODER: 1
  N_LAYERS_DECODER: 1
  DECODER_POS: true
  EMBED_DIM: 24
  LATENT_DIM: 8
  TIME_WINDOW: 25
TRAIN:
  BATCH_SIZE: 128
  BATCH_SIZE_TEST: 1000000
  STEP_SIZE: 1
  STEP_SIZE_TEST: 10
  NUM_UPDATES: 50
  CLIP_GRAD_NORM: 0.5
  LR:
    INIT: 0.005
    SCHEDULE: true
    SCHEDULER: cosine
    WARMUP: 10
  WEIGHT_DECAY: 0.01
  BETA: 0.1
  CHECKPOINT_INTERVAL: 100000
  LOGS_PER_EPOCH: 4
  VAL_INTERVAL: 4
  VAL_DRAW_INTERVAL: 1000000
  SHOW_PLOTS: false
