SEED: 1
RESULT_DIR: results/
FIG_DIR: figs/
RUN_DIR: runs/
DATA:
  RAT: '025'
  TEST_FOLD: 0
  DAY: '2020-07-16'
  TASK: 1MC
PREPROCESS:
  BIN_SIZE: 0.1
  BEFORE_CUE_LONG: 2
  BEFORE_CUE: 0
  AFTER_CUE: 0
  BEFORE_PRESS: 1
  AFTER_PRESS: 0.5
  AFTER_RELEASE: 1
  AFTER_RELEASE_LONG: 2
MODEL:
  NAME: LDF
  DIM_Y: 16
  LATENT_DIM: 6
  TIME_WINDOW: 25
TRAIN:
  n_init: 3
  n_iter: 5
  STEP_SIZE: 1
  STEP_SIZE_TEST: 10
