SEED: 1
RESULT_DIR: results/
FIG_DIR: figs/
RUN_DIR: runs/
DATA:
  RAT: '025'
  TEST_FOLD: 0
  DAY: '2020-07-16'
  TASK: 1MC
PREPROCESS:
  BIN_SIZE: 0.1
  BEFORE_CUE_LONG: 2
  BEFORE_CUE: 0
  AFTER_CUE: 0
  BEFORE_PRESS: 1
  AFTER_PRESS: 0.5
  AFTER_RELEASE: 1
  AFTER_RELEASE_LONG: 2
MODEL:
  NAME: LFADS
  ENCOD_DATA_DIM: 16
  ENCOD_SEQ_LEN: 25
  RECON_SEQ_LEN: 25
  TIME_WINDOW: 25
  EXT_INPUT_DIM: 0
  IC_ENC_SEQ_LEN: 0
  IC_ENC_DIM: 32
  CI_LAG: 1
  CI_ENC_DIM: 0
  CON_DIM: 0
  CO_DIM: 0
  IC_DIM: 32
  GEN_DIM: 32
  LATENT_DIM: 6
DROPOUT_RATE: 0.3
CELL_CLIP: 5.0
LOSS_SCALE: 1.0
RECON_REDUCE_MEAN: true
IC_POST_VAR_MIN: 0.0001
TRAIN:
  NUM_UPDATES: 50
  CLIP_GRAD_NORM: 0.5
  BATCH_SIZE: 128
  BATCH_SIZE_TEST: 1000000
  STEP_SIZE: 1
  STEP_SIZE_TEST: 10
  VAL_INTERVAL: 5
  LOGS_PER_EPOCH: 4
  WEIGHT_DECAY: 0.01
  LR:
    INIT: 0.005
    SCHEDULE: true
    SCHEDULER: cosine
    WARMUP: 10
  L2_START_EPOCH: 0
  L2_INCREASE_EPOCH: 80
  L2_IC_ENC_SCALE: 0.0
  L2_CI_ENC_SCALE: 0.0
  L2_GEN_SCALE: 0.0
  L2_CON_SCALE: 0.0
  KL_START_EPOCH: 0
  KL_INCREASE_EPOCH: 80
  KL_IC_SCALE: 1.0e-07
  KL_CO_SCALE: 1.0e-07
